language: python

sudo: false

os:
  - linux

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  
script:
  - pytest -rx --flake8 --cov astropy_bot astropy_bot
  - python run.py --skip-run

after_success:
  - codecov
