[tool.astropy-bot-experimental]

[ tool.astropy-bot-experimental.milestones ]

enabled = true

[tool.astropy-bot-experimental.pull_requests]

enabled = true
post_pr_comment = false
skip_labels = ["Experimental", "Work in progress"]
skip_fails = true
